name: async_button_builder
description: A builder to wrap around buttons that handles loading, disabled,
  error and success states
version: 3.1.0
homepage: https://github.com/Nolence/async_button/tree/main/packages/async_button_builder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0

# flutter:
